### ISSUE TITLE
Missing edges

### ISSUE THREAD

**Issue by Snehal1894** [songw01/MEGENA#26]
Hello I am trying to run MEGENA on my dataset of  ~3000 genes and while plotting the hierarchy 
I get following issue.

![Screenshot from 2024-08-16 15-03-10](https://github.com/user-attachments/assets/f40397b8-f177-4500-afb8-bbfd34c331f8)

So I tried running the steps on 100 genes , and this how the module table looks, (from this table looks like the network is missing connection information for node c1_2)
![Screenshot from 2024-08-16 15-02-55](https://github.com/user-attachments/assets/1a517e38-d31e-4c4f-b7fa-b850093b7308)

Any suggestions on what could be cause of this bug ? any help would be appreciated. Thank you.

**Comment by MithilG** [comment]
Hi Snehal1894,
Did you add any constraints in the summary function, min and max size?
I suppose you must be filtering out the modules who do not pass the threshold, ex: modules less than 10 size must be getting filtered out if you are assigning min.size=10.

**Comment by Snehal1894** [comment]
Hi @MithilG ,
I looked into my code and removed the min max constraints and I do get fully connected structure. Thank you. I appreciate your response.
