### ISSUE TITLE
Should the experssion data be log-transformed for the co-expression analysis?

### ISSUE THREAD

**Issue by liu-ying-jun** [songw01/MEGENA#5]
Hi 
I am using MEGENA for co-expression analysis. the package is very cool. My gene expression data is in CPM format. I tried to do the co-expression analysis with both cpm values and log2(cpm +1) values. unexpectly, the results were completely different with the two approaches. I am wondering which values should be used for MEGENA? the cpm or log2(cpm +1)? thanks.

**Comment by songw01** [comment]
You should run on log-transformed data.

**Comment by liu-ying-jun** [comment]
I see. thanks a lot. for the co-expression analysis, would you recommend to run it only on the significant gene list (say FDR < 0.05) or on all genes that have expression values in the dataset?

**Comment by songw01** [comment]
You should run on all genes that have substantial variances across the samples (e.g. coefficient of variation > 0.1 is a widely used threshold).

**Comment by liu-ying-jun** [comment]
Great. very helpful. thanks a lot.

**Comment by liu-ying-jun** [comment]
thanks. the cv should be calculated before or after the log transformation?

**Comment by songw01** [comment]
You are assuming normal distribution when calculating CV. Thus, you should do it after log transformation.
