### ISSUE TITLE
Error when using ddMEGENA()!

### ISSUE THREAD

**Issue by ashaypatel** [songw01/MEGENA#8]
I am getting this error when I run ddMEGENA() with my ddcor() results.

`Error in serial.PFN(sortedEdge = ijw, Ng = N, maxENum = maxENum) : The input PFG has exceeding number of edges.`

All of my other other data sets (created from identical pipelines) seem to work fine, however I am having this issue?
I don't know what this issue means and why I am having it.

Any suggestions or tips would be much appreciated.

Thank you for you time,
Ashay

**Comment by mcleoj2** [comment]
Hi There, 

I appear to be receiving the same error when trying to run ddMEGENA() with ddCor(). I can see this issue is closed, so if there is any insight on how to overcome this issue, it would be much appreciated! 

Thanks, 
Jon
